eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
