
words: 

server:
  port: 0

---
spring:
  profiles: subject

words: I,You,He,She,It

server:
  port: 0

---
spring:
  profiles: verb

words: ran,knew,had,saw,bought

server:
  port: 0

---
spring:
  profiles: article

words: a,the

server:
  port: 0

---
spring:
  profiles: adjective

words: reasonable,suspicious,ordinary,unlikely

server:
  port: 0

---
spring:
  profiles: noun

words: boat,movie,book,vote,seat,backpack,partition

server:
  port: 0
